@baseUrl = http://localhost:3000

### AppControllerGetHello

# @name AppController
GET {{baseUrl}}/home/hello

### ExemploDeRota
# @name ConceitosManualControllerHome
GET {{baseUrl}}/conceitos-manual/

### ConceitosAutomaticoController Home
# @name ConceitosAutomaticoControllerHome
GET {{baseUrl}}/conceitos-automatico/

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=10
&user=mateus

### Lista apenas um recado
GET {{baseUrl}}/recados/2/

### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Novo Recado",
    "de": "Joana",
    "para": "Joao",
    "lido": false,
    "data": "2024-08-08T11:32:39.6242" 
}

### Atualiza um recado
PATCH  {{baseUrl}}/recados/2/
Content-Type: application/json

{
    "texto": "Novo Recado",
    "de": "Joana",
    "para": "Joao",
    "lido": false,
    "data": "2024-08-08T11:32:39.6242" 
}

### Deleta um recado
DELETE {{baseUrl}}/recados/2

### Busca todas as músicas
POST{{baseUrl}}/songs
Content-Type: application/json 
{
  
}